### ISSUE TITLE
Better Achievements - spacer disappearing

### ISSUE THREAD

**Issue by pparmy** [rasitayaz/steam-deck-themes#8]
https://github.com/rasitayaz/steam-deck-themes/assets/116443069/84b87105-4bca-4222-86ce-cbb974cd073d

pay attention to the left spacer on the "No Man Left Behind" achievement

**Comment by pparmy** [comment]
![image](https://github.com/rasitayaz/steam-deck-themes/assets/116443069/07b80a85-139a-4368-abf0-fa23488b2eb9)
also an issue on these pages as well (not sure if fixing it in one area would fix it everywhere as I don't know CSS but that's why i mentioned it)

**Comment by pparmy** [comment]
I feel bad bothering you again but it seems like the issue persist under the "Friend" tab when viewing a stand of achievements as shown in the video. I was able to get the issue to persist after turning off Better Achievements but upon restarting steamOS it seems to have fixed itself until I turn it back on. I've reinstalled it too but that hasn't helped.

**Comment by rasitayaz** [comment]
you're right, I overlooked that part
